/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SummariesRouteImport } from './routes/summaries'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentsIndexRouteImport } from './routes/documents.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as DocumentsDocIdRouteImport } from './routes/documents.$docId'
import { Route as CoursesModuleIdRouteImport } from './routes/courses.$moduleId'
import { Route as AdminCatalogRouteImport } from './routes/admin.catalog'
import { Route as DocumentsDocIdIndexRouteImport } from './routes/documents.$docId.index'
import { Route as CoursesModuleIdIndexRouteImport } from './routes/courses.$moduleId.index'
import { Route as DocumentsCollectionsCollectionIdRouteImport } from './routes/documents.collections.$collectionId'
import { Route as DocumentsDocIdSummaryRouteImport } from './routes/documents.$docId.summary'
import { Route as DocumentsCollectionsCollectionIdIndexRouteImport } from './routes/documents.collections.$collectionId.index'
import { Route as DocumentsCollectionsCollectionIdChatRouteImport } from './routes/documents.collections.$collectionId.chat'
import { Route as CoursesModuleIdSummaryDocIdRouteImport } from './routes/courses.$moduleId.summary.$docId'
import { Route as CoursesModuleIdReadDocIdRouteImport } from './routes/courses.$moduleId.read.$docId'

const SummariesRoute = SummariesRouteImport.update({
  id: '/summaries',
  path: '/summaries',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocumentsRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const DocumentsDocIdRoute = DocumentsDocIdRouteImport.update({
  id: '/$docId',
  path: '/$docId',
  getParentRoute: () => DocumentsRoute,
} as any)
const CoursesModuleIdRoute = CoursesModuleIdRouteImport.update({
  id: '/$moduleId',
  path: '/$moduleId',
  getParentRoute: () => CoursesRoute,
} as any)
const AdminCatalogRoute = AdminCatalogRouteImport.update({
  id: '/admin/catalog',
  path: '/admin/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsDocIdIndexRoute = DocumentsDocIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocumentsDocIdRoute,
} as any)
const CoursesModuleIdIndexRoute = CoursesModuleIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesModuleIdRoute,
} as any)
const DocumentsCollectionsCollectionIdRoute =
  DocumentsCollectionsCollectionIdRouteImport.update({
    id: '/collections/$collectionId',
    path: '/collections/$collectionId',
    getParentRoute: () => DocumentsRoute,
  } as any)
const DocumentsDocIdSummaryRoute = DocumentsDocIdSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => DocumentsDocIdRoute,
} as any)
const DocumentsCollectionsCollectionIdIndexRoute =
  DocumentsCollectionsCollectionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DocumentsCollectionsCollectionIdRoute,
  } as any)
const DocumentsCollectionsCollectionIdChatRoute =
  DocumentsCollectionsCollectionIdChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => DocumentsCollectionsCollectionIdRoute,
  } as any)
const CoursesModuleIdSummaryDocIdRoute =
  CoursesModuleIdSummaryDocIdRouteImport.update({
    id: '/summary/$docId',
    path: '/summary/$docId',
    getParentRoute: () => CoursesModuleIdRoute,
  } as any)
const CoursesModuleIdReadDocIdRoute =
  CoursesModuleIdReadDocIdRouteImport.update({
    id: '/read/$docId',
    path: '/read/$docId',
    getParentRoute: () => CoursesModuleIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/signup': typeof SignupRoute
  '/summaries': typeof SummariesRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/courses/$moduleId': typeof CoursesModuleIdRouteWithChildren
  '/documents/$docId': typeof DocumentsDocIdRouteWithChildren
  '/courses/': typeof CoursesIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/documents/$docId/summary': typeof DocumentsDocIdSummaryRoute
  '/documents/collections/$collectionId': typeof DocumentsCollectionsCollectionIdRouteWithChildren
  '/courses/$moduleId/': typeof CoursesModuleIdIndexRoute
  '/documents/$docId/': typeof DocumentsDocIdIndexRoute
  '/courses/$moduleId/read/$docId': typeof CoursesModuleIdReadDocIdRoute
  '/courses/$moduleId/summary/$docId': typeof CoursesModuleIdSummaryDocIdRoute
  '/documents/collections/$collectionId/chat': typeof DocumentsCollectionsCollectionIdChatRoute
  '/documents/collections/$collectionId/': typeof DocumentsCollectionsCollectionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/signup': typeof SignupRoute
  '/summaries': typeof SummariesRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/courses': typeof CoursesIndexRoute
  '/documents': typeof DocumentsIndexRoute
  '/documents/$docId/summary': typeof DocumentsDocIdSummaryRoute
  '/courses/$moduleId': typeof CoursesModuleIdIndexRoute
  '/documents/$docId': typeof DocumentsDocIdIndexRoute
  '/courses/$moduleId/read/$docId': typeof CoursesModuleIdReadDocIdRoute
  '/courses/$moduleId/summary/$docId': typeof CoursesModuleIdSummaryDocIdRoute
  '/documents/collections/$collectionId/chat': typeof DocumentsCollectionsCollectionIdChatRoute
  '/documents/collections/$collectionId': typeof DocumentsCollectionsCollectionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/signup': typeof SignupRoute
  '/summaries': typeof SummariesRoute
  '/admin/catalog': typeof AdminCatalogRoute
  '/courses/$moduleId': typeof CoursesModuleIdRouteWithChildren
  '/documents/$docId': typeof DocumentsDocIdRouteWithChildren
  '/courses/': typeof CoursesIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/documents/$docId/summary': typeof DocumentsDocIdSummaryRoute
  '/documents/collections/$collectionId': typeof DocumentsCollectionsCollectionIdRouteWithChildren
  '/courses/$moduleId/': typeof CoursesModuleIdIndexRoute
  '/documents/$docId/': typeof DocumentsDocIdIndexRoute
  '/courses/$moduleId/read/$docId': typeof CoursesModuleIdReadDocIdRoute
  '/courses/$moduleId/summary/$docId': typeof CoursesModuleIdSummaryDocIdRoute
  '/documents/collections/$collectionId/chat': typeof DocumentsCollectionsCollectionIdChatRoute
  '/documents/collections/$collectionId/': typeof DocumentsCollectionsCollectionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assistant'
    | '/courses'
    | '/dashboard'
    | '/documents'
    | '/login'
    | '/profile'
    | '/progress'
    | '/signup'
    | '/summaries'
    | '/admin/catalog'
    | '/courses/$moduleId'
    | '/documents/$docId'
    | '/courses/'
    | '/documents/'
    | '/documents/$docId/summary'
    | '/documents/collections/$collectionId'
    | '/courses/$moduleId/'
    | '/documents/$docId/'
    | '/courses/$moduleId/read/$docId'
    | '/courses/$moduleId/summary/$docId'
    | '/documents/collections/$collectionId/chat'
    | '/documents/collections/$collectionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/dashboard'
    | '/login'
    | '/profile'
    | '/progress'
    | '/signup'
    | '/summaries'
    | '/admin/catalog'
    | '/courses'
    | '/documents'
    | '/documents/$docId/summary'
    | '/courses/$moduleId'
    | '/documents/$docId'
    | '/courses/$moduleId/read/$docId'
    | '/courses/$moduleId/summary/$docId'
    | '/documents/collections/$collectionId/chat'
    | '/documents/collections/$collectionId'
  id:
    | '__root__'
    | '/'
    | '/assistant'
    | '/courses'
    | '/dashboard'
    | '/documents'
    | '/login'
    | '/profile'
    | '/progress'
    | '/signup'
    | '/summaries'
    | '/admin/catalog'
    | '/courses/$moduleId'
    | '/documents/$docId'
    | '/courses/'
    | '/documents/'
    | '/documents/$docId/summary'
    | '/documents/collections/$collectionId'
    | '/courses/$moduleId/'
    | '/documents/$docId/'
    | '/courses/$moduleId/read/$docId'
    | '/courses/$moduleId/summary/$docId'
    | '/documents/collections/$collectionId/chat'
    | '/documents/collections/$collectionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssistantRoute: typeof AssistantRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  SignupRoute: typeof SignupRoute
  SummariesRoute: typeof SummariesRoute
  AdminCatalogRoute: typeof AdminCatalogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/summaries': {
      id: '/summaries'
      path: '/summaries'
      fullPath: '/summaries'
      preLoaderRoute: typeof SummariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/': {
      id: '/documents/'
      path: '/'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/documents/$docId': {
      id: '/documents/$docId'
      path: '/$docId'
      fullPath: '/documents/$docId'
      preLoaderRoute: typeof DocumentsDocIdRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/courses/$moduleId': {
      id: '/courses/$moduleId'
      path: '/$moduleId'
      fullPath: '/courses/$moduleId'
      preLoaderRoute: typeof CoursesModuleIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/admin/catalog': {
      id: '/admin/catalog'
      path: '/admin/catalog'
      fullPath: '/admin/catalog'
      preLoaderRoute: typeof AdminCatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/$docId/': {
      id: '/documents/$docId/'
      path: '/'
      fullPath: '/documents/$docId/'
      preLoaderRoute: typeof DocumentsDocIdIndexRouteImport
      parentRoute: typeof DocumentsDocIdRoute
    }
    '/courses/$moduleId/': {
      id: '/courses/$moduleId/'
      path: '/'
      fullPath: '/courses/$moduleId/'
      preLoaderRoute: typeof CoursesModuleIdIndexRouteImport
      parentRoute: typeof CoursesModuleIdRoute
    }
    '/documents/collections/$collectionId': {
      id: '/documents/collections/$collectionId'
      path: '/collections/$collectionId'
      fullPath: '/documents/collections/$collectionId'
      preLoaderRoute: typeof DocumentsCollectionsCollectionIdRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/documents/$docId/summary': {
      id: '/documents/$docId/summary'
      path: '/summary'
      fullPath: '/documents/$docId/summary'
      preLoaderRoute: typeof DocumentsDocIdSummaryRouteImport
      parentRoute: typeof DocumentsDocIdRoute
    }
    '/documents/collections/$collectionId/': {
      id: '/documents/collections/$collectionId/'
      path: '/'
      fullPath: '/documents/collections/$collectionId/'
      preLoaderRoute: typeof DocumentsCollectionsCollectionIdIndexRouteImport
      parentRoute: typeof DocumentsCollectionsCollectionIdRoute
    }
    '/documents/collections/$collectionId/chat': {
      id: '/documents/collections/$collectionId/chat'
      path: '/chat'
      fullPath: '/documents/collections/$collectionId/chat'
      preLoaderRoute: typeof DocumentsCollectionsCollectionIdChatRouteImport
      parentRoute: typeof DocumentsCollectionsCollectionIdRoute
    }
    '/courses/$moduleId/summary/$docId': {
      id: '/courses/$moduleId/summary/$docId'
      path: '/summary/$docId'
      fullPath: '/courses/$moduleId/summary/$docId'
      preLoaderRoute: typeof CoursesModuleIdSummaryDocIdRouteImport
      parentRoute: typeof CoursesModuleIdRoute
    }
    '/courses/$moduleId/read/$docId': {
      id: '/courses/$moduleId/read/$docId'
      path: '/read/$docId'
      fullPath: '/courses/$moduleId/read/$docId'
      preLoaderRoute: typeof CoursesModuleIdReadDocIdRouteImport
      parentRoute: typeof CoursesModuleIdRoute
    }
  }
}

interface CoursesModuleIdRouteChildren {
  CoursesModuleIdIndexRoute: typeof CoursesModuleIdIndexRoute
  CoursesModuleIdReadDocIdRoute: typeof CoursesModuleIdReadDocIdRoute
  CoursesModuleIdSummaryDocIdRoute: typeof CoursesModuleIdSummaryDocIdRoute
}

const CoursesModuleIdRouteChildren: CoursesModuleIdRouteChildren = {
  CoursesModuleIdIndexRoute: CoursesModuleIdIndexRoute,
  CoursesModuleIdReadDocIdRoute: CoursesModuleIdReadDocIdRoute,
  CoursesModuleIdSummaryDocIdRoute: CoursesModuleIdSummaryDocIdRoute,
}

const CoursesModuleIdRouteWithChildren = CoursesModuleIdRoute._addFileChildren(
  CoursesModuleIdRouteChildren,
)

interface CoursesRouteChildren {
  CoursesModuleIdRoute: typeof CoursesModuleIdRouteWithChildren
  CoursesIndexRoute: typeof CoursesIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesModuleIdRoute: CoursesModuleIdRouteWithChildren,
  CoursesIndexRoute: CoursesIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface DocumentsDocIdRouteChildren {
  DocumentsDocIdSummaryRoute: typeof DocumentsDocIdSummaryRoute
  DocumentsDocIdIndexRoute: typeof DocumentsDocIdIndexRoute
}

const DocumentsDocIdRouteChildren: DocumentsDocIdRouteChildren = {
  DocumentsDocIdSummaryRoute: DocumentsDocIdSummaryRoute,
  DocumentsDocIdIndexRoute: DocumentsDocIdIndexRoute,
}

const DocumentsDocIdRouteWithChildren = DocumentsDocIdRoute._addFileChildren(
  DocumentsDocIdRouteChildren,
)

interface DocumentsCollectionsCollectionIdRouteChildren {
  DocumentsCollectionsCollectionIdChatRoute: typeof DocumentsCollectionsCollectionIdChatRoute
  DocumentsCollectionsCollectionIdIndexRoute: typeof DocumentsCollectionsCollectionIdIndexRoute
}

const DocumentsCollectionsCollectionIdRouteChildren: DocumentsCollectionsCollectionIdRouteChildren =
  {
    DocumentsCollectionsCollectionIdChatRoute:
      DocumentsCollectionsCollectionIdChatRoute,
    DocumentsCollectionsCollectionIdIndexRoute:
      DocumentsCollectionsCollectionIdIndexRoute,
  }

const DocumentsCollectionsCollectionIdRouteWithChildren =
  DocumentsCollectionsCollectionIdRoute._addFileChildren(
    DocumentsCollectionsCollectionIdRouteChildren,
  )

interface DocumentsRouteChildren {
  DocumentsDocIdRoute: typeof DocumentsDocIdRouteWithChildren
  DocumentsIndexRoute: typeof DocumentsIndexRoute
  DocumentsCollectionsCollectionIdRoute: typeof DocumentsCollectionsCollectionIdRouteWithChildren
}

const DocumentsRouteChildren: DocumentsRouteChildren = {
  DocumentsDocIdRoute: DocumentsDocIdRouteWithChildren,
  DocumentsIndexRoute: DocumentsIndexRoute,
  DocumentsCollectionsCollectionIdRoute:
    DocumentsCollectionsCollectionIdRouteWithChildren,
}

const DocumentsRouteWithChildren = DocumentsRoute._addFileChildren(
  DocumentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssistantRoute: AssistantRoute,
  CoursesRoute: CoursesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRouteWithChildren,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  SignupRoute: SignupRoute,
  SummariesRoute: SummariesRoute,
  AdminCatalogRoute: AdminCatalogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
