/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TutorialsRouteImport } from './routes/tutorials'
import { Route as SummariesRouteImport } from './routes/summaries'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProgressRouteImport } from './routes/progress'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocumentsIndexRouteImport } from './routes/documents.index'
import { Route as CoursesIndexRouteImport } from './routes/courses.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DocumentsDocIdRouteImport } from './routes/documents.$docId'
import { Route as CoursesModuleIdRouteImport } from './routes/courses.$moduleId'
import { Route as AdminSuperRouteImport } from './routes/admin.super'
import { Route as AdminFeedbackRouteImport } from './routes/admin.feedback'
import { Route as DocumentsDocIdIndexRouteImport } from './routes/documents.$docId.index'
import { Route as CoursesMoodleIndexRouteImport } from './routes/courses.moodle.index'
import { Route as CoursesModuleIdIndexRouteImport } from './routes/courses.$moduleId.index'
import { Route as AdminSuperIndexRouteImport } from './routes/admin.super.index'
import { Route as AdminModulesIndexRouteImport } from './routes/admin.modules.index'
import { Route as DocumentsCollectionsCollectionIdRouteImport } from './routes/documents.collections.$collectionId'
import { Route as DocumentsDocIdViewRouteImport } from './routes/documents.$docId.view'
import { Route as DocumentsDocIdSummaryRouteImport } from './routes/documents.$docId.summary'
import { Route as DocumentsDocIdQuizRouteImport } from './routes/documents.$docId.quiz'
import { Route as DocumentsDocIdNotesRouteImport } from './routes/documents.$docId.notes'
import { Route as DocumentsDocIdFlashcardsRouteImport } from './routes/documents.$docId.flashcards'
import { Route as DocumentsDocIdChatRouteImport } from './routes/documents.$docId.chat'
import { Route as CoursesMoodleCourseIdRouteImport } from './routes/courses.moodle.$courseId'
import { Route as AdminSuperUsersRouteImport } from './routes/admin.super.users'
import { Route as AdminSuperResearchRouteImport } from './routes/admin.super.research'
import { Route as AdminModulesNewRouteImport } from './routes/admin.modules.new'
import { Route as AdminModulesModuleIdRouteImport } from './routes/admin.modules.$moduleId'
import { Route as DocumentsCollectionsCollectionIdIndexRouteImport } from './routes/documents.collections.$collectionId.index'
import { Route as CoursesModuleIdChatIndexRouteImport } from './routes/courses.$moduleId.chat.index'
import { Route as DocumentsCollectionsCollectionIdQuizRouteImport } from './routes/documents.collections.$collectionId.quiz'
import { Route as DocumentsCollectionsCollectionIdFlashcardsRouteImport } from './routes/documents.collections.$collectionId.flashcards'
import { Route as DocumentsCollectionsCollectionIdChatRouteImport } from './routes/documents.collections.$collectionId.chat'
import { Route as CoursesModuleIdSummaryDocIdRouteImport } from './routes/courses.$moduleId.summary.$docId'
import { Route as CoursesModuleIdReadDocIdRouteImport } from './routes/courses.$moduleId.read.$docId'
import { Route as CoursesModuleIdQuizDocIdRouteImport } from './routes/courses.$moduleId.quiz.$docId'
import { Route as CoursesModuleIdFlashcardsDocIdRouteImport } from './routes/courses.$moduleId.flashcards.$docId'
import { Route as CoursesModuleIdChatDocIdRouteImport } from './routes/courses.$moduleId.chat.$docId'

const TutorialsRoute = TutorialsRouteImport.update({
  id: '/tutorials',
  path: '/tutorials',
  getParentRoute: () => rootRouteImport,
} as any)
const SummariesRoute = SummariesRouteImport.update({
  id: '/summaries',
  path: '/summaries',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressRoute = ProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsIndexRoute = DocumentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocumentsRoute,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DocumentsDocIdRoute = DocumentsDocIdRouteImport.update({
  id: '/$docId',
  path: '/$docId',
  getParentRoute: () => DocumentsRoute,
} as any)
const CoursesModuleIdRoute = CoursesModuleIdRouteImport.update({
  id: '/$moduleId',
  path: '/$moduleId',
  getParentRoute: () => CoursesRoute,
} as any)
const AdminSuperRoute = AdminSuperRouteImport.update({
  id: '/super',
  path: '/super',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFeedbackRoute = AdminFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AdminRoute,
} as any)
const DocumentsDocIdIndexRoute = DocumentsDocIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DocumentsDocIdRoute,
} as any)
const CoursesMoodleIndexRoute = CoursesMoodleIndexRouteImport.update({
  id: '/moodle/',
  path: '/moodle/',
  getParentRoute: () => CoursesRoute,
} as any)
const CoursesModuleIdIndexRoute = CoursesModuleIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CoursesModuleIdRoute,
} as any)
const AdminSuperIndexRoute = AdminSuperIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSuperRoute,
} as any)
const AdminModulesIndexRoute = AdminModulesIndexRouteImport.update({
  id: '/modules/',
  path: '/modules/',
  getParentRoute: () => AdminRoute,
} as any)
const DocumentsCollectionsCollectionIdRoute =
  DocumentsCollectionsCollectionIdRouteImport.update({
    id: '/collections/$collectionId',
    path: '/collections/$collectionId',
    getParentRoute: () => DocumentsRoute,
  } as any)
const DocumentsDocIdViewRoute = DocumentsDocIdViewRouteImport.update({
  id: '/view',
  path: '/view',
  getParentRoute: () => DocumentsDocIdRoute,
} as any)
const DocumentsDocIdSummaryRoute = DocumentsDocIdSummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => DocumentsDocIdRoute,
} as any)
const DocumentsDocIdQuizRoute = DocumentsDocIdQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => DocumentsDocIdRoute,
} as any)
const DocumentsDocIdNotesRoute = DocumentsDocIdNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => DocumentsDocIdRoute,
} as any)
const DocumentsDocIdFlashcardsRoute =
  DocumentsDocIdFlashcardsRouteImport.update({
    id: '/flashcards',
    path: '/flashcards',
    getParentRoute: () => DocumentsDocIdRoute,
  } as any)
const DocumentsDocIdChatRoute = DocumentsDocIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => DocumentsDocIdRoute,
} as any)
const CoursesMoodleCourseIdRoute = CoursesMoodleCourseIdRouteImport.update({
  id: '/moodle/$courseId',
  path: '/moodle/$courseId',
  getParentRoute: () => CoursesRoute,
} as any)
const AdminSuperUsersRoute = AdminSuperUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminSuperRoute,
} as any)
const AdminSuperResearchRoute = AdminSuperResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AdminSuperRoute,
} as any)
const AdminModulesNewRoute = AdminModulesNewRouteImport.update({
  id: '/modules/new',
  path: '/modules/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModulesModuleIdRoute = AdminModulesModuleIdRouteImport.update({
  id: '/modules/$moduleId',
  path: '/modules/$moduleId',
  getParentRoute: () => AdminRoute,
} as any)
const DocumentsCollectionsCollectionIdIndexRoute =
  DocumentsCollectionsCollectionIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => DocumentsCollectionsCollectionIdRoute,
  } as any)
const CoursesModuleIdChatIndexRoute =
  CoursesModuleIdChatIndexRouteImport.update({
    id: '/chat/',
    path: '/chat/',
    getParentRoute: () => CoursesModuleIdRoute,
  } as any)
const DocumentsCollectionsCollectionIdQuizRoute =
  DocumentsCollectionsCollectionIdQuizRouteImport.update({
    id: '/quiz',
    path: '/quiz',
    getParentRoute: () => DocumentsCollectionsCollectionIdRoute,
  } as any)
const DocumentsCollectionsCollectionIdFlashcardsRoute =
  DocumentsCollectionsCollectionIdFlashcardsRouteImport.update({
    id: '/flashcards',
    path: '/flashcards',
    getParentRoute: () => DocumentsCollectionsCollectionIdRoute,
  } as any)
const DocumentsCollectionsCollectionIdChatRoute =
  DocumentsCollectionsCollectionIdChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => DocumentsCollectionsCollectionIdRoute,
  } as any)
const CoursesModuleIdSummaryDocIdRoute =
  CoursesModuleIdSummaryDocIdRouteImport.update({
    id: '/summary/$docId',
    path: '/summary/$docId',
    getParentRoute: () => CoursesModuleIdRoute,
  } as any)
const CoursesModuleIdReadDocIdRoute =
  CoursesModuleIdReadDocIdRouteImport.update({
    id: '/read/$docId',
    path: '/read/$docId',
    getParentRoute: () => CoursesModuleIdRoute,
  } as any)
const CoursesModuleIdQuizDocIdRoute =
  CoursesModuleIdQuizDocIdRouteImport.update({
    id: '/quiz/$docId',
    path: '/quiz/$docId',
    getParentRoute: () => CoursesModuleIdRoute,
  } as any)
const CoursesModuleIdFlashcardsDocIdRoute =
  CoursesModuleIdFlashcardsDocIdRouteImport.update({
    id: '/flashcards/$docId',
    path: '/flashcards/$docId',
    getParentRoute: () => CoursesModuleIdRoute,
  } as any)
const CoursesModuleIdChatDocIdRoute =
  CoursesModuleIdChatDocIdRouteImport.update({
    id: '/chat/$docId',
    path: '/chat/$docId',
    getParentRoute: () => CoursesModuleIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/legal': typeof LegalRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/summaries': typeof SummariesRoute
  '/tutorials': typeof TutorialsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/super': typeof AdminSuperRouteWithChildren
  '/courses/$moduleId': typeof CoursesModuleIdRouteWithChildren
  '/documents/$docId': typeof DocumentsDocIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/admin/modules/$moduleId': typeof AdminModulesModuleIdRoute
  '/admin/modules/new': typeof AdminModulesNewRoute
  '/admin/super/research': typeof AdminSuperResearchRoute
  '/admin/super/users': typeof AdminSuperUsersRoute
  '/courses/moodle/$courseId': typeof CoursesMoodleCourseIdRoute
  '/documents/$docId/chat': typeof DocumentsDocIdChatRoute
  '/documents/$docId/flashcards': typeof DocumentsDocIdFlashcardsRoute
  '/documents/$docId/notes': typeof DocumentsDocIdNotesRoute
  '/documents/$docId/quiz': typeof DocumentsDocIdQuizRoute
  '/documents/$docId/summary': typeof DocumentsDocIdSummaryRoute
  '/documents/$docId/view': typeof DocumentsDocIdViewRoute
  '/documents/collections/$collectionId': typeof DocumentsCollectionsCollectionIdRouteWithChildren
  '/admin/modules/': typeof AdminModulesIndexRoute
  '/admin/super/': typeof AdminSuperIndexRoute
  '/courses/$moduleId/': typeof CoursesModuleIdIndexRoute
  '/courses/moodle/': typeof CoursesMoodleIndexRoute
  '/documents/$docId/': typeof DocumentsDocIdIndexRoute
  '/courses/$moduleId/chat/$docId': typeof CoursesModuleIdChatDocIdRoute
  '/courses/$moduleId/flashcards/$docId': typeof CoursesModuleIdFlashcardsDocIdRoute
  '/courses/$moduleId/quiz/$docId': typeof CoursesModuleIdQuizDocIdRoute
  '/courses/$moduleId/read/$docId': typeof CoursesModuleIdReadDocIdRoute
  '/courses/$moduleId/summary/$docId': typeof CoursesModuleIdSummaryDocIdRoute
  '/documents/collections/$collectionId/chat': typeof DocumentsCollectionsCollectionIdChatRoute
  '/documents/collections/$collectionId/flashcards': typeof DocumentsCollectionsCollectionIdFlashcardsRoute
  '/documents/collections/$collectionId/quiz': typeof DocumentsCollectionsCollectionIdQuizRoute
  '/courses/$moduleId/chat/': typeof CoursesModuleIdChatIndexRoute
  '/documents/collections/$collectionId/': typeof DocumentsCollectionsCollectionIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assistant': typeof AssistantRoute
  '/dashboard': typeof DashboardRoute
  '/legal': typeof LegalRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/summaries': typeof SummariesRoute
  '/tutorials': typeof TutorialsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin': typeof AdminIndexRoute
  '/courses': typeof CoursesIndexRoute
  '/documents': typeof DocumentsIndexRoute
  '/admin/modules/$moduleId': typeof AdminModulesModuleIdRoute
  '/admin/modules/new': typeof AdminModulesNewRoute
  '/admin/super/research': typeof AdminSuperResearchRoute
  '/admin/super/users': typeof AdminSuperUsersRoute
  '/courses/moodle/$courseId': typeof CoursesMoodleCourseIdRoute
  '/documents/$docId/chat': typeof DocumentsDocIdChatRoute
  '/documents/$docId/flashcards': typeof DocumentsDocIdFlashcardsRoute
  '/documents/$docId/notes': typeof DocumentsDocIdNotesRoute
  '/documents/$docId/quiz': typeof DocumentsDocIdQuizRoute
  '/documents/$docId/summary': typeof DocumentsDocIdSummaryRoute
  '/documents/$docId/view': typeof DocumentsDocIdViewRoute
  '/admin/modules': typeof AdminModulesIndexRoute
  '/admin/super': typeof AdminSuperIndexRoute
  '/courses/$moduleId': typeof CoursesModuleIdIndexRoute
  '/courses/moodle': typeof CoursesMoodleIndexRoute
  '/documents/$docId': typeof DocumentsDocIdIndexRoute
  '/courses/$moduleId/chat/$docId': typeof CoursesModuleIdChatDocIdRoute
  '/courses/$moduleId/flashcards/$docId': typeof CoursesModuleIdFlashcardsDocIdRoute
  '/courses/$moduleId/quiz/$docId': typeof CoursesModuleIdQuizDocIdRoute
  '/courses/$moduleId/read/$docId': typeof CoursesModuleIdReadDocIdRoute
  '/courses/$moduleId/summary/$docId': typeof CoursesModuleIdSummaryDocIdRoute
  '/documents/collections/$collectionId/chat': typeof DocumentsCollectionsCollectionIdChatRoute
  '/documents/collections/$collectionId/flashcards': typeof DocumentsCollectionsCollectionIdFlashcardsRoute
  '/documents/collections/$collectionId/quiz': typeof DocumentsCollectionsCollectionIdQuizRoute
  '/courses/$moduleId/chat': typeof CoursesModuleIdChatIndexRoute
  '/documents/collections/$collectionId': typeof DocumentsCollectionsCollectionIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/assistant': typeof AssistantRoute
  '/courses': typeof CoursesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRouteWithChildren
  '/legal': typeof LegalRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/progress': typeof ProgressRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/summaries': typeof SummariesRoute
  '/tutorials': typeof TutorialsRoute
  '/admin/feedback': typeof AdminFeedbackRoute
  '/admin/super': typeof AdminSuperRouteWithChildren
  '/courses/$moduleId': typeof CoursesModuleIdRouteWithChildren
  '/documents/$docId': typeof DocumentsDocIdRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/courses/': typeof CoursesIndexRoute
  '/documents/': typeof DocumentsIndexRoute
  '/admin/modules/$moduleId': typeof AdminModulesModuleIdRoute
  '/admin/modules/new': typeof AdminModulesNewRoute
  '/admin/super/research': typeof AdminSuperResearchRoute
  '/admin/super/users': typeof AdminSuperUsersRoute
  '/courses/moodle/$courseId': typeof CoursesMoodleCourseIdRoute
  '/documents/$docId/chat': typeof DocumentsDocIdChatRoute
  '/documents/$docId/flashcards': typeof DocumentsDocIdFlashcardsRoute
  '/documents/$docId/notes': typeof DocumentsDocIdNotesRoute
  '/documents/$docId/quiz': typeof DocumentsDocIdQuizRoute
  '/documents/$docId/summary': typeof DocumentsDocIdSummaryRoute
  '/documents/$docId/view': typeof DocumentsDocIdViewRoute
  '/documents/collections/$collectionId': typeof DocumentsCollectionsCollectionIdRouteWithChildren
  '/admin/modules/': typeof AdminModulesIndexRoute
  '/admin/super/': typeof AdminSuperIndexRoute
  '/courses/$moduleId/': typeof CoursesModuleIdIndexRoute
  '/courses/moodle/': typeof CoursesMoodleIndexRoute
  '/documents/$docId/': typeof DocumentsDocIdIndexRoute
  '/courses/$moduleId/chat/$docId': typeof CoursesModuleIdChatDocIdRoute
  '/courses/$moduleId/flashcards/$docId': typeof CoursesModuleIdFlashcardsDocIdRoute
  '/courses/$moduleId/quiz/$docId': typeof CoursesModuleIdQuizDocIdRoute
  '/courses/$moduleId/read/$docId': typeof CoursesModuleIdReadDocIdRoute
  '/courses/$moduleId/summary/$docId': typeof CoursesModuleIdSummaryDocIdRoute
  '/documents/collections/$collectionId/chat': typeof DocumentsCollectionsCollectionIdChatRoute
  '/documents/collections/$collectionId/flashcards': typeof DocumentsCollectionsCollectionIdFlashcardsRoute
  '/documents/collections/$collectionId/quiz': typeof DocumentsCollectionsCollectionIdQuizRoute
  '/courses/$moduleId/chat/': typeof CoursesModuleIdChatIndexRoute
  '/documents/collections/$collectionId/': typeof DocumentsCollectionsCollectionIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assistant'
    | '/courses'
    | '/dashboard'
    | '/documents'
    | '/legal'
    | '/library'
    | '/login'
    | '/profile'
    | '/progress'
    | '/settings'
    | '/signup'
    | '/summaries'
    | '/tutorials'
    | '/admin/feedback'
    | '/admin/super'
    | '/courses/$moduleId'
    | '/documents/$docId'
    | '/admin/'
    | '/courses/'
    | '/documents/'
    | '/admin/modules/$moduleId'
    | '/admin/modules/new'
    | '/admin/super/research'
    | '/admin/super/users'
    | '/courses/moodle/$courseId'
    | '/documents/$docId/chat'
    | '/documents/$docId/flashcards'
    | '/documents/$docId/notes'
    | '/documents/$docId/quiz'
    | '/documents/$docId/summary'
    | '/documents/$docId/view'
    | '/documents/collections/$collectionId'
    | '/admin/modules/'
    | '/admin/super/'
    | '/courses/$moduleId/'
    | '/courses/moodle/'
    | '/documents/$docId/'
    | '/courses/$moduleId/chat/$docId'
    | '/courses/$moduleId/flashcards/$docId'
    | '/courses/$moduleId/quiz/$docId'
    | '/courses/$moduleId/read/$docId'
    | '/courses/$moduleId/summary/$docId'
    | '/documents/collections/$collectionId/chat'
    | '/documents/collections/$collectionId/flashcards'
    | '/documents/collections/$collectionId/quiz'
    | '/courses/$moduleId/chat/'
    | '/documents/collections/$collectionId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assistant'
    | '/dashboard'
    | '/legal'
    | '/library'
    | '/login'
    | '/profile'
    | '/progress'
    | '/settings'
    | '/signup'
    | '/summaries'
    | '/tutorials'
    | '/admin/feedback'
    | '/admin'
    | '/courses'
    | '/documents'
    | '/admin/modules/$moduleId'
    | '/admin/modules/new'
    | '/admin/super/research'
    | '/admin/super/users'
    | '/courses/moodle/$courseId'
    | '/documents/$docId/chat'
    | '/documents/$docId/flashcards'
    | '/documents/$docId/notes'
    | '/documents/$docId/quiz'
    | '/documents/$docId/summary'
    | '/documents/$docId/view'
    | '/admin/modules'
    | '/admin/super'
    | '/courses/$moduleId'
    | '/courses/moodle'
    | '/documents/$docId'
    | '/courses/$moduleId/chat/$docId'
    | '/courses/$moduleId/flashcards/$docId'
    | '/courses/$moduleId/quiz/$docId'
    | '/courses/$moduleId/read/$docId'
    | '/courses/$moduleId/summary/$docId'
    | '/documents/collections/$collectionId/chat'
    | '/documents/collections/$collectionId/flashcards'
    | '/documents/collections/$collectionId/quiz'
    | '/courses/$moduleId/chat'
    | '/documents/collections/$collectionId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/assistant'
    | '/courses'
    | '/dashboard'
    | '/documents'
    | '/legal'
    | '/library'
    | '/login'
    | '/profile'
    | '/progress'
    | '/settings'
    | '/signup'
    | '/summaries'
    | '/tutorials'
    | '/admin/feedback'
    | '/admin/super'
    | '/courses/$moduleId'
    | '/documents/$docId'
    | '/admin/'
    | '/courses/'
    | '/documents/'
    | '/admin/modules/$moduleId'
    | '/admin/modules/new'
    | '/admin/super/research'
    | '/admin/super/users'
    | '/courses/moodle/$courseId'
    | '/documents/$docId/chat'
    | '/documents/$docId/flashcards'
    | '/documents/$docId/notes'
    | '/documents/$docId/quiz'
    | '/documents/$docId/summary'
    | '/documents/$docId/view'
    | '/documents/collections/$collectionId'
    | '/admin/modules/'
    | '/admin/super/'
    | '/courses/$moduleId/'
    | '/courses/moodle/'
    | '/documents/$docId/'
    | '/courses/$moduleId/chat/$docId'
    | '/courses/$moduleId/flashcards/$docId'
    | '/courses/$moduleId/quiz/$docId'
    | '/courses/$moduleId/read/$docId'
    | '/courses/$moduleId/summary/$docId'
    | '/documents/collections/$collectionId/chat'
    | '/documents/collections/$collectionId/flashcards'
    | '/documents/collections/$collectionId/quiz'
    | '/courses/$moduleId/chat/'
    | '/documents/collections/$collectionId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AssistantRoute: typeof AssistantRoute
  CoursesRoute: typeof CoursesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRouteWithChildren
  LegalRoute: typeof LegalRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ProgressRoute: typeof ProgressRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SummariesRoute: typeof SummariesRoute
  TutorialsRoute: typeof TutorialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tutorials': {
      id: '/tutorials'
      path: '/tutorials'
      fullPath: '/tutorials'
      preLoaderRoute: typeof TutorialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summaries': {
      id: '/summaries'
      path: '/summaries'
      fullPath: '/summaries'
      preLoaderRoute: typeof SummariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progress': {
      id: '/progress'
      path: '/progress'
      fullPath: '/progress'
      preLoaderRoute: typeof ProgressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents/': {
      id: '/documents/'
      path: '/'
      fullPath: '/documents/'
      preLoaderRoute: typeof DocumentsIndexRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/courses/': {
      id: '/courses/'
      path: '/'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/documents/$docId': {
      id: '/documents/$docId'
      path: '/$docId'
      fullPath: '/documents/$docId'
      preLoaderRoute: typeof DocumentsDocIdRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/courses/$moduleId': {
      id: '/courses/$moduleId'
      path: '/$moduleId'
      fullPath: '/courses/$moduleId'
      preLoaderRoute: typeof CoursesModuleIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/admin/super': {
      id: '/admin/super'
      path: '/super'
      fullPath: '/admin/super'
      preLoaderRoute: typeof AdminSuperRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/feedback': {
      id: '/admin/feedback'
      path: '/feedback'
      fullPath: '/admin/feedback'
      preLoaderRoute: typeof AdminFeedbackRouteImport
      parentRoute: typeof AdminRoute
    }
    '/documents/$docId/': {
      id: '/documents/$docId/'
      path: '/'
      fullPath: '/documents/$docId/'
      preLoaderRoute: typeof DocumentsDocIdIndexRouteImport
      parentRoute: typeof DocumentsDocIdRoute
    }
    '/courses/moodle/': {
      id: '/courses/moodle/'
      path: '/moodle'
      fullPath: '/courses/moodle/'
      preLoaderRoute: typeof CoursesMoodleIndexRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/courses/$moduleId/': {
      id: '/courses/$moduleId/'
      path: '/'
      fullPath: '/courses/$moduleId/'
      preLoaderRoute: typeof CoursesModuleIdIndexRouteImport
      parentRoute: typeof CoursesModuleIdRoute
    }
    '/admin/super/': {
      id: '/admin/super/'
      path: '/'
      fullPath: '/admin/super/'
      preLoaderRoute: typeof AdminSuperIndexRouteImport
      parentRoute: typeof AdminSuperRoute
    }
    '/admin/modules/': {
      id: '/admin/modules/'
      path: '/modules'
      fullPath: '/admin/modules/'
      preLoaderRoute: typeof AdminModulesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/documents/collections/$collectionId': {
      id: '/documents/collections/$collectionId'
      path: '/collections/$collectionId'
      fullPath: '/documents/collections/$collectionId'
      preLoaderRoute: typeof DocumentsCollectionsCollectionIdRouteImport
      parentRoute: typeof DocumentsRoute
    }
    '/documents/$docId/view': {
      id: '/documents/$docId/view'
      path: '/view'
      fullPath: '/documents/$docId/view'
      preLoaderRoute: typeof DocumentsDocIdViewRouteImport
      parentRoute: typeof DocumentsDocIdRoute
    }
    '/documents/$docId/summary': {
      id: '/documents/$docId/summary'
      path: '/summary'
      fullPath: '/documents/$docId/summary'
      preLoaderRoute: typeof DocumentsDocIdSummaryRouteImport
      parentRoute: typeof DocumentsDocIdRoute
    }
    '/documents/$docId/quiz': {
      id: '/documents/$docId/quiz'
      path: '/quiz'
      fullPath: '/documents/$docId/quiz'
      preLoaderRoute: typeof DocumentsDocIdQuizRouteImport
      parentRoute: typeof DocumentsDocIdRoute
    }
    '/documents/$docId/notes': {
      id: '/documents/$docId/notes'
      path: '/notes'
      fullPath: '/documents/$docId/notes'
      preLoaderRoute: typeof DocumentsDocIdNotesRouteImport
      parentRoute: typeof DocumentsDocIdRoute
    }
    '/documents/$docId/flashcards': {
      id: '/documents/$docId/flashcards'
      path: '/flashcards'
      fullPath: '/documents/$docId/flashcards'
      preLoaderRoute: typeof DocumentsDocIdFlashcardsRouteImport
      parentRoute: typeof DocumentsDocIdRoute
    }
    '/documents/$docId/chat': {
      id: '/documents/$docId/chat'
      path: '/chat'
      fullPath: '/documents/$docId/chat'
      preLoaderRoute: typeof DocumentsDocIdChatRouteImport
      parentRoute: typeof DocumentsDocIdRoute
    }
    '/courses/moodle/$courseId': {
      id: '/courses/moodle/$courseId'
      path: '/moodle/$courseId'
      fullPath: '/courses/moodle/$courseId'
      preLoaderRoute: typeof CoursesMoodleCourseIdRouteImport
      parentRoute: typeof CoursesRoute
    }
    '/admin/super/users': {
      id: '/admin/super/users'
      path: '/users'
      fullPath: '/admin/super/users'
      preLoaderRoute: typeof AdminSuperUsersRouteImport
      parentRoute: typeof AdminSuperRoute
    }
    '/admin/super/research': {
      id: '/admin/super/research'
      path: '/research'
      fullPath: '/admin/super/research'
      preLoaderRoute: typeof AdminSuperResearchRouteImport
      parentRoute: typeof AdminSuperRoute
    }
    '/admin/modules/new': {
      id: '/admin/modules/new'
      path: '/modules/new'
      fullPath: '/admin/modules/new'
      preLoaderRoute: typeof AdminModulesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modules/$moduleId': {
      id: '/admin/modules/$moduleId'
      path: '/modules/$moduleId'
      fullPath: '/admin/modules/$moduleId'
      preLoaderRoute: typeof AdminModulesModuleIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/documents/collections/$collectionId/': {
      id: '/documents/collections/$collectionId/'
      path: '/'
      fullPath: '/documents/collections/$collectionId/'
      preLoaderRoute: typeof DocumentsCollectionsCollectionIdIndexRouteImport
      parentRoute: typeof DocumentsCollectionsCollectionIdRoute
    }
    '/courses/$moduleId/chat/': {
      id: '/courses/$moduleId/chat/'
      path: '/chat'
      fullPath: '/courses/$moduleId/chat/'
      preLoaderRoute: typeof CoursesModuleIdChatIndexRouteImport
      parentRoute: typeof CoursesModuleIdRoute
    }
    '/documents/collections/$collectionId/quiz': {
      id: '/documents/collections/$collectionId/quiz'
      path: '/quiz'
      fullPath: '/documents/collections/$collectionId/quiz'
      preLoaderRoute: typeof DocumentsCollectionsCollectionIdQuizRouteImport
      parentRoute: typeof DocumentsCollectionsCollectionIdRoute
    }
    '/documents/collections/$collectionId/flashcards': {
      id: '/documents/collections/$collectionId/flashcards'
      path: '/flashcards'
      fullPath: '/documents/collections/$collectionId/flashcards'
      preLoaderRoute: typeof DocumentsCollectionsCollectionIdFlashcardsRouteImport
      parentRoute: typeof DocumentsCollectionsCollectionIdRoute
    }
    '/documents/collections/$collectionId/chat': {
      id: '/documents/collections/$collectionId/chat'
      path: '/chat'
      fullPath: '/documents/collections/$collectionId/chat'
      preLoaderRoute: typeof DocumentsCollectionsCollectionIdChatRouteImport
      parentRoute: typeof DocumentsCollectionsCollectionIdRoute
    }
    '/courses/$moduleId/summary/$docId': {
      id: '/courses/$moduleId/summary/$docId'
      path: '/summary/$docId'
      fullPath: '/courses/$moduleId/summary/$docId'
      preLoaderRoute: typeof CoursesModuleIdSummaryDocIdRouteImport
      parentRoute: typeof CoursesModuleIdRoute
    }
    '/courses/$moduleId/read/$docId': {
      id: '/courses/$moduleId/read/$docId'
      path: '/read/$docId'
      fullPath: '/courses/$moduleId/read/$docId'
      preLoaderRoute: typeof CoursesModuleIdReadDocIdRouteImport
      parentRoute: typeof CoursesModuleIdRoute
    }
    '/courses/$moduleId/quiz/$docId': {
      id: '/courses/$moduleId/quiz/$docId'
      path: '/quiz/$docId'
      fullPath: '/courses/$moduleId/quiz/$docId'
      preLoaderRoute: typeof CoursesModuleIdQuizDocIdRouteImport
      parentRoute: typeof CoursesModuleIdRoute
    }
    '/courses/$moduleId/flashcards/$docId': {
      id: '/courses/$moduleId/flashcards/$docId'
      path: '/flashcards/$docId'
      fullPath: '/courses/$moduleId/flashcards/$docId'
      preLoaderRoute: typeof CoursesModuleIdFlashcardsDocIdRouteImport
      parentRoute: typeof CoursesModuleIdRoute
    }
    '/courses/$moduleId/chat/$docId': {
      id: '/courses/$moduleId/chat/$docId'
      path: '/chat/$docId'
      fullPath: '/courses/$moduleId/chat/$docId'
      preLoaderRoute: typeof CoursesModuleIdChatDocIdRouteImport
      parentRoute: typeof CoursesModuleIdRoute
    }
  }
}

interface AdminSuperRouteChildren {
  AdminSuperResearchRoute: typeof AdminSuperResearchRoute
  AdminSuperUsersRoute: typeof AdminSuperUsersRoute
  AdminSuperIndexRoute: typeof AdminSuperIndexRoute
}

const AdminSuperRouteChildren: AdminSuperRouteChildren = {
  AdminSuperResearchRoute: AdminSuperResearchRoute,
  AdminSuperUsersRoute: AdminSuperUsersRoute,
  AdminSuperIndexRoute: AdminSuperIndexRoute,
}

const AdminSuperRouteWithChildren = AdminSuperRoute._addFileChildren(
  AdminSuperRouteChildren,
)

interface AdminRouteChildren {
  AdminFeedbackRoute: typeof AdminFeedbackRoute
  AdminSuperRoute: typeof AdminSuperRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
  AdminModulesModuleIdRoute: typeof AdminModulesModuleIdRoute
  AdminModulesNewRoute: typeof AdminModulesNewRoute
  AdminModulesIndexRoute: typeof AdminModulesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminFeedbackRoute: AdminFeedbackRoute,
  AdminSuperRoute: AdminSuperRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
  AdminModulesModuleIdRoute: AdminModulesModuleIdRoute,
  AdminModulesNewRoute: AdminModulesNewRoute,
  AdminModulesIndexRoute: AdminModulesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CoursesModuleIdRouteChildren {
  CoursesModuleIdIndexRoute: typeof CoursesModuleIdIndexRoute
  CoursesModuleIdChatDocIdRoute: typeof CoursesModuleIdChatDocIdRoute
  CoursesModuleIdFlashcardsDocIdRoute: typeof CoursesModuleIdFlashcardsDocIdRoute
  CoursesModuleIdQuizDocIdRoute: typeof CoursesModuleIdQuizDocIdRoute
  CoursesModuleIdReadDocIdRoute: typeof CoursesModuleIdReadDocIdRoute
  CoursesModuleIdSummaryDocIdRoute: typeof CoursesModuleIdSummaryDocIdRoute
  CoursesModuleIdChatIndexRoute: typeof CoursesModuleIdChatIndexRoute
}

const CoursesModuleIdRouteChildren: CoursesModuleIdRouteChildren = {
  CoursesModuleIdIndexRoute: CoursesModuleIdIndexRoute,
  CoursesModuleIdChatDocIdRoute: CoursesModuleIdChatDocIdRoute,
  CoursesModuleIdFlashcardsDocIdRoute: CoursesModuleIdFlashcardsDocIdRoute,
  CoursesModuleIdQuizDocIdRoute: CoursesModuleIdQuizDocIdRoute,
  CoursesModuleIdReadDocIdRoute: CoursesModuleIdReadDocIdRoute,
  CoursesModuleIdSummaryDocIdRoute: CoursesModuleIdSummaryDocIdRoute,
  CoursesModuleIdChatIndexRoute: CoursesModuleIdChatIndexRoute,
}

const CoursesModuleIdRouteWithChildren = CoursesModuleIdRoute._addFileChildren(
  CoursesModuleIdRouteChildren,
)

interface CoursesRouteChildren {
  CoursesModuleIdRoute: typeof CoursesModuleIdRouteWithChildren
  CoursesIndexRoute: typeof CoursesIndexRoute
  CoursesMoodleCourseIdRoute: typeof CoursesMoodleCourseIdRoute
  CoursesMoodleIndexRoute: typeof CoursesMoodleIndexRoute
}

const CoursesRouteChildren: CoursesRouteChildren = {
  CoursesModuleIdRoute: CoursesModuleIdRouteWithChildren,
  CoursesIndexRoute: CoursesIndexRoute,
  CoursesMoodleCourseIdRoute: CoursesMoodleCourseIdRoute,
  CoursesMoodleIndexRoute: CoursesMoodleIndexRoute,
}

const CoursesRouteWithChildren =
  CoursesRoute._addFileChildren(CoursesRouteChildren)

interface DocumentsDocIdRouteChildren {
  DocumentsDocIdChatRoute: typeof DocumentsDocIdChatRoute
  DocumentsDocIdFlashcardsRoute: typeof DocumentsDocIdFlashcardsRoute
  DocumentsDocIdNotesRoute: typeof DocumentsDocIdNotesRoute
  DocumentsDocIdQuizRoute: typeof DocumentsDocIdQuizRoute
  DocumentsDocIdSummaryRoute: typeof DocumentsDocIdSummaryRoute
  DocumentsDocIdViewRoute: typeof DocumentsDocIdViewRoute
  DocumentsDocIdIndexRoute: typeof DocumentsDocIdIndexRoute
}

const DocumentsDocIdRouteChildren: DocumentsDocIdRouteChildren = {
  DocumentsDocIdChatRoute: DocumentsDocIdChatRoute,
  DocumentsDocIdFlashcardsRoute: DocumentsDocIdFlashcardsRoute,
  DocumentsDocIdNotesRoute: DocumentsDocIdNotesRoute,
  DocumentsDocIdQuizRoute: DocumentsDocIdQuizRoute,
  DocumentsDocIdSummaryRoute: DocumentsDocIdSummaryRoute,
  DocumentsDocIdViewRoute: DocumentsDocIdViewRoute,
  DocumentsDocIdIndexRoute: DocumentsDocIdIndexRoute,
}

const DocumentsDocIdRouteWithChildren = DocumentsDocIdRoute._addFileChildren(
  DocumentsDocIdRouteChildren,
)

interface DocumentsCollectionsCollectionIdRouteChildren {
  DocumentsCollectionsCollectionIdChatRoute: typeof DocumentsCollectionsCollectionIdChatRoute
  DocumentsCollectionsCollectionIdFlashcardsRoute: typeof DocumentsCollectionsCollectionIdFlashcardsRoute
  DocumentsCollectionsCollectionIdQuizRoute: typeof DocumentsCollectionsCollectionIdQuizRoute
  DocumentsCollectionsCollectionIdIndexRoute: typeof DocumentsCollectionsCollectionIdIndexRoute
}

const DocumentsCollectionsCollectionIdRouteChildren: DocumentsCollectionsCollectionIdRouteChildren =
  {
    DocumentsCollectionsCollectionIdChatRoute:
      DocumentsCollectionsCollectionIdChatRoute,
    DocumentsCollectionsCollectionIdFlashcardsRoute:
      DocumentsCollectionsCollectionIdFlashcardsRoute,
    DocumentsCollectionsCollectionIdQuizRoute:
      DocumentsCollectionsCollectionIdQuizRoute,
    DocumentsCollectionsCollectionIdIndexRoute:
      DocumentsCollectionsCollectionIdIndexRoute,
  }

const DocumentsCollectionsCollectionIdRouteWithChildren =
  DocumentsCollectionsCollectionIdRoute._addFileChildren(
    DocumentsCollectionsCollectionIdRouteChildren,
  )

interface DocumentsRouteChildren {
  DocumentsDocIdRoute: typeof DocumentsDocIdRouteWithChildren
  DocumentsIndexRoute: typeof DocumentsIndexRoute
  DocumentsCollectionsCollectionIdRoute: typeof DocumentsCollectionsCollectionIdRouteWithChildren
}

const DocumentsRouteChildren: DocumentsRouteChildren = {
  DocumentsDocIdRoute: DocumentsDocIdRouteWithChildren,
  DocumentsIndexRoute: DocumentsIndexRoute,
  DocumentsCollectionsCollectionIdRoute:
    DocumentsCollectionsCollectionIdRouteWithChildren,
}

const DocumentsRouteWithChildren = DocumentsRoute._addFileChildren(
  DocumentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AssistantRoute: AssistantRoute,
  CoursesRoute: CoursesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRouteWithChildren,
  LegalRoute: LegalRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ProgressRoute: ProgressRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SummariesRoute: SummariesRoute,
  TutorialsRoute: TutorialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
